# common
proj_name: posml_project_1
model_name: posml_project_1
model_version: v0.1

# Data Management
mart_id: dm_f_20085_2212_142

# workflow management
time_zone: Asia/Seoul
date_format: "%Y-%m-%d %H:%M:%S"

train_start_date: "2023-03-19 00:00:00"
train_schedule_interval: "@daily"

train_trigger_start_date: "2023-03-19 00:00:00"
train_trigger_schedule_interval: "@daily"

# resource management
git_repo: https://github.com/koni114/airflow_train_pipeline_1.git
git_branch: main
git_mount_root_path: /projects
git_sync_image_repository: k8s.gcr.io/git-sync
git_sync_image_tag: v3.1.1
train_pipeline_image_repository: koni114/python
train_pipeline_image_tag: 3.8-test-2